# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 20:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hotel.app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_img', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default=b'Titulo de la Imagen', max_length=200)),
                ('pic', models.ImageField(upload_to=hotel.app.models.get_img_url)),
            ],
            options={
                'ordering': ['id_piso'],
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id_piso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[(b'PISO', b'Piso'), (b'HABITACION', b'Habitacion')], default=b'PISO', max_length=10)),
                ('lat', models.FloatField(default=0.0, null=True)),
                ('lng', models.FloatField(default=0.0, null=True)),
                ('descripcion', models.TextField(blank=True, verbose_name=b'Descripcion')),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('fecha_registro', models.DateField(default=datetime.date.today, verbose_name=b'Fecha registro')),
                ('precio', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id_piso'],
                'verbose_name_plural': 'Pisos',
            },
        ),
        migrations.AddField(
            model_name='imagen',
            name='id_piso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Piso'),
        ),
    ]
