# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160531_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['id_habitacion'], 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='user',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='camas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='planta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[(b'Fumador', b'Fumador'), (b'NoFumador', b'No fumador')], default=b'NoFumador', max_length=10),
        ),
    ]
