# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160531_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='titulo',
            field=models.CharField(default=b'Doble', max_length=200),
        ),
    ]
